# Generated by Django 4.2.6 on 2023-11-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Images', models.ImageField(upload_to='picture/')),
            ],
            options={
                'db_table': 'Image_table',
            },
        ),
    ]
